added env reading feature
kube-tarian/kubviz pull request #3
Opened 2022-04-04 11:54 UTC by vijeyash1

2022-04-06 18:13 UTC, avinashkna4 requested changes

2022-04-06 18:13 UTC, avinashkna4 commented on clickhouse/clickhouse_client.go
> +	connect, err := sql.Open(dbAdress, "tcp://clickhouse:9009?debug=true")
1. you have modified database type . First parameter should not be changed. Please revert it  
2. read both host and port separately and replace envs in second parameter "tcp://clickhouse:9009?debug=true")

2022-04-06 18:13 UTC, avinashkna4 commented on agent/k8smetrics_agent.go
> +	//, nats.Token("UfmrJOYwYCCsgQvxvcfJ3BdI6c8WBbnD")
remove this comment

2022-04-06 18:13 UTC, avinashkna4 commented on client/k8smetrics_client.go
> +	//, nats.Token("UfmrJOYwYCCsgQvxvcfJ3BdI6c8WBbnD")
remove this token  comment as well

2022-04-06 18:13 UTC, avinashkna4 commented on clickhouse/clickhouse_client.go
> +	connect, err := sql.Open(dbAdress, "tcp://clickhouse:9009?debug=true")
also please test all the changes before merging it

2022-04-07 01:25 UTC, vijeyash1 commented
Thank you for the feedback bro. Sure Will make the changes bro.

On Wed, Apr 6, 2022, 11:43 PM Avinash K N ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In clickhouse/clickhouse_client.go
> <https://github.com/kube-tarian/kubviz/pull/3#discussion_r844243850>:
>
> >  func GetClickHouseConnection() (*sql.DB, error) {
> -	connect, err := sql.Open("clickhouse", "tcp://clickhouse:9009?debug=true")
> +	connect, err := sql.Open(dbAdress, "tcp://clickhouse:9009?debug=true")
>
>
>    1. you have modified database type . First parameter should not be
>    changed. Please revert it
>    2. read both host and port separately and replace envs in second
>    parameter "tcp://clickhouse:9009?debug=true")
>
> ------------------------------
>
> In agent/k8smetrics_agent.go
> <https://github.com/kube-tarian/kubviz/pull/3#discussion_r844245077>:
>
> >  func main() {
>
>  	// Connect to NATS
> -	nc, err := nats.Connect("nats", nats.Name("K8s Metrics"), nats.Token("UfmrJOYwYCCsgQvxvcfJ3BdI6c8WBbnD"))
> +	//, nats.Token("UfmrJOYwYCCsgQvxvcfJ3BdI6c8WBbnD")
>
> remove this comment
> ------------------------------
>
> In client/k8smetrics_client.go
> <https://github.com/kube-tarian/kubviz/pull/3#discussion_r844245538>:
>
> >  func main() {
>
>  	// Connect to NATS
> -	nc, err := nats.Connect("nats", nats.Name("K8s Metrics"), nats.Token("UfmrJOYwYCCsgQvxvcfJ3BdI6c8WBbnD"))
> +
> +	//, nats.Token("UfmrJOYwYCCsgQvxvcfJ3BdI6c8WBbnD")
>
> remove this token comment as well
> ------------------------------
>
> In clickhouse/clickhouse_client.go
> <https://github.com/kube-tarian/kubviz/pull/3#discussion_r844246132>:
>
> >  func GetClickHouseConnection() (*sql.DB, error) {
> -	connect, err := sql.Open("clickhouse", "tcp://clickhouse:9009?debug=true")
> +	connect, err := sql.Open(dbAdress, "tcp://clickhouse:9009?debug=true")
>
> also please test all the changes before merging it
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kube-tarian/kubviz/pull/3#pullrequestreview-933903039>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVYN2D6XZVTUM3VCYP7FGFLVDXH4VANCNFSM5SPIZY4A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-07 17:36 UTC, avinashkna4 approved these changes

2022-04-10 18:10 UTC, jebinjeb commented
rebuild

2022-04-10 18:18 UTC, merged